spring:
  r2dbc:
    url: ${DATABASE_URL:r2dbc:postgresql://localhost:5432/postgres}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:postgres}
  liquibase:
    change-log: classpath:/config/liquibase/db.changelog-master.yaml
  mvc:
    log-request-details: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql: TRACE
    io.r2dbc.postgresql.QUERY: DEBUG
    org.springframework.r2dbc: DEBUG


server:
  port: ${PORT:8080}